server:
  port: 18104

spring:
  datasource:
    username: root
    password: chen151717
    url: jdbc:mysql://localhost:3306/pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zfcraft.web.entity




#showSql
logging:
  level:
    com:
      example:
        mapper : debug